Iter8
22Fariz22/shorturl pull request #13
Opened 2022-11-24 11:08 UTC by 22Fariz22

2022-11-24 16:20 UTC, shmel1k requested changes

2022-11-24 16:20 UTC, shmel1k commented on cmd/shortener/main.go
> +	"flag"
Что-то не так с go.mod

Не должен быть `22Fariz22/shorturl/repo`, должно быть `github.com/22Fariz22/shorturl/repo`

2022-11-24 16:20 UTC, shmel1k commented on cmd/shortener/main.go
> +	"net/http"
goimports

2022-11-24 16:20 UTC, shmel1k commented on cmd/shortener/main.go
> +		log.Fatal("ListenAndServe: ", err)
Приложение всегда упадёт с фаталом, даже если сервер успешно завершится

Во время завершения работы сервера возникает логичная ошибка `ErrServerClosed`. нужно отдельно её обрабатывать

2022-11-24 16:20 UTC, shmel1k commented on handler/config/config.go
> +//envDefault:"storage/events.json"
Выглядит как забытый комментарий

2022-11-24 16:20 UTC, shmel1k commented on handler/handler.go
goimports

2022-11-24 16:20 UTC, shmel1k commented on handler/handler.go
> +		log.Fatal(err)
Почему Fatal?

2022-11-24 16:20 UTC, shmel1k commented on handler/handler.go
> +		log.Fatal(err)
Почему фатал?

2022-11-24 16:20 UTC, shmel1k commented on handler/handler.go
> +		panic(err)
почему паника?

2022-11-24 16:20 UTC, shmel1k commented on handler/handler.go
> +		log.Fatal(err.Error())
Почему фатал?

2022-11-24 16:20 UTC, shmel1k commented on handler/handler.go
> +
Нужно избавиться от этой копипасты в двух пакетах: handlers & model(кажется). Это можно унести в model

2022-11-24 16:20 UTC, shmel1k commented on repo/repo_handlers.go
> +	file, err := os.OpenFile(cfg.FileStoragePath, os.O_CREATE|os.O_APPEND, 0777)
0777 -- много, хватит 0644

И нужны такие флаги: `os.O_CREATE|os.O_WRONLY|os.O_APPEND`

2022-11-24 16:20 UTC, shmel1k commented on repo/repo_handlers.go
> +		log.Fatal(err)
Почему фатал?

2022-11-24 16:20 UTC, shmel1k commented on repo/repo_handlers.go
> +	_ = json.Unmarshal(b, &alUrls.AllUrls)
Лучше не игнорировать эту ошибку

2022-11-24 16:20 UTC, shmel1k commented on repo/repo_handlers.go
> +		log.Fatal(err)
Не нужно перечитывать файл на каждой записи Эвента, мы это обсуждали. Нужно дописывать в конец файла, перечитывать -- нет

2022-11-24 16:20 UTC, shmel1k commented on repo/repo_handlers.go
> +	ioutil.WriteFile(p.Cfg.FileStoragePath, newURLBytes, 0666)
Лучше не игнорировать ошибку

2022-11-24 16:20 UTC, shmel1k commented on handler/handler.go
> +	h.Mu.Lock()
Лучше вернуть мьютекс так, как было: неэкспортируемым

2022-11-25 12:33 UTC, 22Fariz22 commented on handler/handler.go
> +
из handler убрал, а из repo_handlers не получилось. go пишет что import cycle not allowed

2022-11-25 13:20 UTC, shmel1k requested changes

2022-11-25 13:20 UTC, shmel1k commented on model/model.go
> +}
По поводу go import cycle: лучше унести JSON Model сюда.

2022-11-25 15:25 UTC, 22Fariz22 commented on handler/handler.go
> +	h.Mu.Lock()
тогда HandlerModel надо перенести в handler.go ? иначе mutex не будет экспортироваться

2022-12-02 08:09 UTC, shmel1k approved these changes

2022-12-02 08:09 UTC, shmel1k commented on cmd/shortener/main.go
> +		fileRepo.Init()
Лучше этот Init() перетащить пониже, на 27 строку. И вызывать что для inmemory, что для infile

2022-12-02 08:09 UTC, shmel1k commented on repository/file/file.go
> +		log.Fatal(err)
Не нужно пользоваться фаталами в таком контексте. Просто верните здесь ошибку, а в мейне проверьте, что всё ок

2022-12-02 08:09 UTC, shmel1k commented on he.json
> +{"ID":"01GK87XGA98K7N57F3CHWN2C8P","LongURL":"http://ya.ru"}
Получился како-йто очень длинный айдишник

2022-12-02 08:09 UTC, shmel1k commented on repository/file/file.go
> +		log.Fatal(err)
Почему фатал?

2022-12-02 08:09 UTC, shmel1k commented on repository/file/file.go
> +		log.Println(u)
Похоже на потерянный принт

2022-12-02 08:09 UTC, shmel1k commented on config/config.go
> +		log.Fatal(err)
Почему фатал?

2022-12-06 12:42 UTC, merged