Iter11
22Fariz22/shorturl pull request #16
Opened 2022-12-07 17:06 UTC by 22Fariz22

2022-12-07 21:43 UTC, shmel1k requested changes

2022-12-07 21:43 UTC, shmel1k commented on handler/handler.go
> +	fmt.Println(i)
выглядит как забытый дебаг-принт

2022-12-07 21:43 UTC, shmel1k commented on handler/handler.go
>  		log.Fatal(err)
откуда здесь фатал? Нужно его выпилить

2022-12-07 21:43 UTC, shmel1k commented on handler/handler.go
>  		log.Fatal(err)
А ещё на строчке 156 справа добавить return

2022-12-07 21:43 UTC, shmel1k commented on repository/db/db.go
> +	_, err := i.conn.Exec(ctx, "create table if not exists urls(cookies text, id text,longurl text);")
а где PRIMARY KEY?

2022-12-07 21:43 UTC, shmel1k commented on repository/db/db.go
> +	_, err := i.conn.Exec(ctx, "create table if not exists urls(cookies text, id text,longurl text);")
Это не нужно делать перед каждым запросом. Лучше унести это в Init

2022-12-07 21:43 UTC, shmel1k commented on repository/db/db.go
> +		return nil
Ошибка теряется. Вызывающая сторона будет думать, что всё хорошо

2022-12-07 21:43 UTC, shmel1k commented on repository/db/db.go
> +			return nil
Ошибка теряется. Вызывающая сторона будет думать, что всё хорошо

2022-12-07 21:43 UTC, shmel1k commented on repository/db/db.go
> +	//}
Лишний код

2022-12-08 08:24 UTC, shmel1k requested changes

2022-12-08 08:24 UTC, shmel1k commented on handler/handler.go
> +	}
В случае ошибки вернётся 200, что не есть хорошо

2022-12-08 08:24 UTC, shmel1k commented on handler/handler.go
> +		log.Println(err)
и код пойдёт дальше

2022-12-08 08:24 UTC, shmel1k commented on repository/db/db.go
> +		log.Println(err)
Лучше просто вернуть ошибку

2022-12-08 08:24 UTC, shmel1k commented on repository/db/db.go
> +		log.Println(err)
Ошибку лучше печатать где-то выше, не в репозитории

2022-12-08 11:28 UTC, 22Fariz22 commented on handler/handler.go
> +	}
можно поставить w.WriteHeader(http.StatusNoContent) ?

2022-12-08 11:30 UTC, 22Fariz22 commented on handler/handler.go
> +		log.Println(err)
вернуть log.fatal(err) ?

2022-12-08 11:32 UTC, 22Fariz22 commented on repository/db/db.go
> +		log.Println(err)
а как вернуть ошибку если функция возвращает (string,bool), менять bool на err?

2022-12-08 11:55 UTC, shmel1k commented on handler/handler.go
> +	}
Например, так. Но лучше посмотреть, что там за ошибка, и сделать что-то более умное, нежели просто 201

2022-12-08 11:56 UTC, shmel1k commented on handler/handler.go
> +		log.Println(err)
Нет. Нужно вернуть http ошибку и выйти из функции

2022-12-08 11:58 UTC, shmel1k commented on repository/db/db.go
> +		log.Println(err)
Можно попробовать возвращать ErrNotFound или что-то такое

2022-12-08 13:02 UTC, merged