Iter13
22Fariz22/shorturl pull request #18
Opened 2022-12-10 14:35 UTC by 22Fariz22

2022-12-12 11:35 UTC, shmel1k requested changes

2022-12-12 11:35 UTC, shmel1k commented on handler/handler.go
> +	w.Write([]byte(h.cfg.BaseURL + "/" + s))
Вот это странно выглядит с точки зрения кода. Лучше возвращать ошибку, если получился конфликт УРЛов, а не если урл успешно создался

2022-12-12 11:35 UTC, shmel1k commented on repository/memory/memory.go
> +	return "", errors.New("")
Вот так не нужно. Лучше nil возвращать.

2022-12-12 11:47 UTC, 22Fariz22 commented on handler/handler.go
> +	w.Write([]byte(h.cfg.BaseURL + "/" + s))
да согласен! но мне пришлось переделать хэндлер под saveURL() в db. я не смог там сделать чтобы выдавала правильно ошибку. из-за этого поломалась логика взаимодействия с saveURL() в файле и мемори и как раз это и было причиной  проблемы со статусами.

2022-12-12 11:48 UTC, 22Fariz22 commented on repository/memory/memory.go
> +	return "", errors.New("")
да, это из-за того что я накостылил в saveURL() в db , пришлось переделать хэндлер. и тут nil не прокатывает.

2022-12-12 11:48 UTC, shmel1k commented on handler/handler.go
> +	w.Write([]byte(h.cfg.BaseURL + "/" + s))
Это всё равно нужно переделать и сделать правильно: ошибка нил -- успешно сохранили

2022-12-12 13:34 UTC, 22Fariz22 commented on handler/handler.go
> +	w.Write([]byte(h.cfg.BaseURL + "/" + s))
я не знаю как переделать SaveURL() in db. может посмотрите,
https://github.com/22Fariz22/shorturl/blob/73f2719df8cee78a7f7180abf539f0b3402cfdd9/repository/db/db.go#L61
как правильно сделать?

2022-12-13 06:28 UTC, shmel1k approved these changes

2022-12-13 06:28 UTC, shmel1k commented on handler/handler.go
> +
Лучше спиливать такие паразитные newline-ы. В этом плане хороший форматтер -- gofumpt(как-то так)

2022-12-13 06:28 UTC, shmel1k commented on handler/handler.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 180*time.Second)
3 минуты на таймаут -- многовато как-то

2022-12-13 06:28 UTC, shmel1k commented on repository/db/db.go
> +		return s, errors.New("такой есть")
Вот так лучше не писать)
1. errors.New() тянет на отдельную ошибку вида `var ErrAlreadyExists = errors.New("...")`
2. Описание на кириллице -- нас не поймут)

2022-12-13 15:12 UTC, merged