Iter14
22Fariz22/shorturl pull request #19
Opened 2022-12-25 23:39 UTC by 22Fariz22

2023-01-15 20:02 UTC, Bazys requested changes

2023-01-15 20:02 UTC, Bazys commented on model/model.go
>  type OwnerID struct {
зачем эта структура?

2023-01-15 20:02 UTC, Bazys commented on worker/worker.go
> +type WorkerPool struct {
пакет и так называется worker, поэтому суффикс Worker во всех названиях лишний

2023-01-15 20:02 UTC, Bazys commented on repository/repository.go
>  	Init() error
зачем возвращать ошибку, если ее не проверяешь?

2023-01-16 09:46 UTC, 22Fariz22 commented on repository/repository.go
>  	Init() error
в init() ?

2023-01-18 21:47 UTC, 22Fariz22 commented on repository/repository.go
>  	Init() error
перепроверил,вроде везде проверяется ошибка в хэндлерах. может что-то я не увидел.

2023-01-28 10:47 UTC, Bazys requested changes
доделать работу с контекстом правильно!
а в остальном отличный рефакторинг с учетом правильных практик

2023-01-28 10:47 UTC, Bazys commented on internal/app/app.go
> +	workers.Stop()
я бы это спрятал под defer.
да и log.Fatalf сразу после себя вызывает os.Exit(), так что workers.Stop() не отработает

2023-01-28 10:47 UTC, Bazys commented on internal/handler/handler.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
5 - вытащи в константу
на 147 строке используешь правильный контекст, а тут почему от Background ?

2023-01-28 10:47 UTC, Bazys commented on internal/handler/handler.go
>  	for i := range batchResp {
```suggestion
	for _,resp := range batchResp {
```

2023-01-28 10:47 UTC, Bazys commented on internal/handler/handler.go
>  			CorrelationID: batchResp[i].CorrelationID,
```suggestion
			CorrelationID: resp.CorrelationID,
```

2023-01-28 10:47 UTC, Bazys commented on internal/handler/handler.go
> +	_, cancel := context.WithTimeout(r.Context(), 5*time.Second)
вот начало правильное, но использования нет

2023-01-28 10:47 UTC, Bazys commented on internal/handler/handler.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
аналогично, почему Background а не r.Context()

2023-01-28 14:00 UTC, Bazys approved these changes

2023-01-28 14:08 UTC, merged